### ISSUE TITLE
CFP Open Checklist Draft / work in progress

### ISSUE THREAD

**Issue by adamfast** [djangocon/2022.djangocon.us#12]
- [ ] Announcement blog post for DjangoCon US blog
- [ ] Announcement blog post for DSF blog
- [x] Website ready (enough) for blog to be available
- [x] DCUS site: Speaker info page ready
- [x] DCUS site: Opportunity grant page ready
- [ ] Opportunity grants application Google Form set up and tested / recording into proper Google spreadsheet
- [ ] CFP platform links to opportunity grants application
- [ ] CFP platform set up, primary organizers added, blind review policies etc configured
- [x] Determine open/close dates of Opportunity Grant application period, dates of recipient announcement
- [x] Determine open/close dates of CFP application period, dates of talk acceptance notification and public announcement
- [ ] Email CFP open to previous speakers?
- [ ] Django News coverage request
- [ ] ReadTheDocs community ad request https://docs.readthedocs.io/en/stable/advertising/ethical-advertising.html#community-ads

What else do we need to do / review?

**Comment by jefftriplett** [comment]
# Dates (as they appear in our pull requests):

## Conference Days:
  - Sunday, October 16: Tutorials
  - Monday, October 17: Talks Day 1
  - Tuesday, October 18: Talks Day 2
  - Wednesday, October 19: Talks Day 3 aka Deep Dive day
  - Thursday, October 20: Sprints Day 1
  - Thursday, October 21: Sprints Day 2

## CFP
  - start date: 2022-05-10
  - end date: 2022-05-31
  - notified by date: 2022-06-24

## Opportunity Grants
  - start date: 2022-05-10
  - end date: 2022-05-31
  - notified by date: 2022-06-24
